name: Build

on:
  push:
    branches: [ 'master' ]
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'
  pull_request:
    branches: [ 'master' ]
    paths-ignore:
      - '**/README.md'
      - '**/.gitignore'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        include:
          - java: '17'
            target: JVM
            task: jvmTest
          - java: '17'
            target: JS
            task: jsTest
    runs-on: ubuntu-latest
    name: Build (${{ matrix.java }} / ${{ matrix.target }})
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}

      - name: Cache Konan
        uses: actions/cache@v3
        with:
          path: ~/.konan
          key: ${{ runner.os }}-konan-${{ github.sha }}
          restore-keys: ${{ runner.os }}-konan-

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run Build and Tests (${{ matrix.target }})
        run: ./gradlew ${{ matrix.task }}
        working-directory: ${{ github.workspace }}
        continue-on-error: false
